
FROM opensuse

RUN zypper install -y \
    make \
    pandoc \
    python # Texlive setup needs python

RUN zypper install -y \
    texliveonfly


#    texlive-enumitem \
#    texlive-floatrow \
#    texlive-import \
#    texlive-latex \
#    texlive-latexmk \
#    texlive-subfig \
#    texlive-svg \
#    texlive-tex-gyre \
#    texlive-ulem

CMD ["/bin/bash"]
